version: "3"

services:
  app:
    build: ./app
    command: ["nginx", "-g", "daemon off;"]
  e2e:
    build: ./e2e
    depends_on:
      app:
        condition: service_started
    environment:
      - CYPRESS_baseUrl=http://app:80
    command: ["cypress", "run"]
