name: app-deploy

on:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: 'app'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Lint and test
        run: | 
          yarn lint &&
          yarn test

      - name: Build
        run: yarn build
