name: app-deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install dependencies
        run: yarn install

      - name: lint and test
        run: | 
          yarn lint &&
          yarn test

      - name: build
        run: yarn build
