name: network

on:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: 'app'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Lint and test
        run: | 
          yarn lint &&
          yarn test

      - name: Prepare build
        run: yarn build

      - name: Build docker image
        run: | 
          docker build -t test-cypress-app:latest . &&
          docker tag test-cypress-app:latest ${{ secrets.DOCKER_USERNAME }}/test-cypress-app:latest

      - name: Pull docker e2e image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/test-cypress-e2e:latest

      - name: E2E test
        run: |
          docker network create local-network
          docker run -d --name app --network local-network test-cypress-app
          docker run --rm --name e2e --network local-network -e CYPRESS_baseUrl=http://app:80 ${{ secrets.DOCKER_USERNAME }}/test-cypress-e2e

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push app image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/test-cypress-app:latest
