name: compose

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd app &&
          yarn install &&
          yarn lint &&
          yarn test &&
          yarn build &&
          cd ..

      - name: Run compose
        run: docker-compose up --exit-code-from e2e | grep -v app
